apiVersion: caps.in.tum.fastgshare/v1
kind: FaSTFunc
metadata:
  name: fastfunc-resnet
  namespace: fast-gshare-fn
  annotations:
    "min-qps": "10"
    "gpu-preferred": "V100"
spec:
  modelName: resnet
  minQps: 10
  allocationType: FASTPOD
  podSpec:
    containers:
    - name: resnet-pytorch
      image: ishworgiri/resnet:pytorch
      ports:
        - containerPort: 8080
      readinessProbe:
        tcpSocket:
          port: 5000
        initialDelaySeconds: 5
        periodSeconds: 10
      volumeMounts:
        - name: "model-volume"
          mountPath: "/models/"
      # command: ["/bin/bash", "-c"]
      # args: ["sleep 7200"]
    volumes:
        - name: "model-volume"
          hostPath:
            path: "/models/"